apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
spec:
  selector:
    app: hello-api
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
spec:
  selector:
    matchLabels:
      app: hello-api
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
      - name: hello-api
        image: hello-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000